### ISSUE TITLE
Not work in KB v1.0.38

### ISSUE THREAD

**Issue by EdwardNavarro** [trajche/SamlAuth#2]
Hi guys, the SAML plugins not work in kanboard 1.0.38.

After send the data with the "Generate Metadata" button, shows the next message:

`Internal Error: Invalid array settings: sp_entityId_not_found, sp_acs_not_found, sp_sls_url_invalid, sp_certs_not_found_and_required, contact_not_enought_data`

**Comment by trajche** [comment]
Hi Edward - have you filled out the config details before you generate the metadata?

**Comment by EdwardNavarro** [comment]
Hi @trajche, We discover few problems with the plugin.

1. When I install the plugin, not create the setting records in the database table, even, not save any records and changes in this. We create the settings records manually in the DB table and work, i can see the settings in the form (Settings > Integrations > SAML), I can see the Metadata file and set the configuration in my IDP.

2. After set all settings correct, I try to login, put my credentials in the SSO login form and this redirect to my kanboard installation, but only show the login page again, not authenticate the user. I try setting the attributes in many forms but this not work. I audit the saml response and my SSO send all attributes correct, log the session in the DB, but kanboard cant authenticate.

**Comment by smacz42** [comment]
I can confirm the same behavior in 1.0.41. Can you help me troubleshoot by letting me know where/how the table/s are are supposed to be created and populated?

![screenshot-2017-23-01](https://cloud.githubusercontent.com/assets/10110994/24341758/f7375e66-1289-11e7-9de0-22262c671433.png)

**Comment by smacz42** [comment]
I found that I had to hit "save" before I hit "generate metadata".

**Comment by julio1501** [comment]
@EdwardNavarro 
hi do you have a solution of that. I have the same issue on my kanboard installation. I can retrieve all attributes from the idp, but KB shows the "normal" login form again

Thanks

**Comment by LizardM4** [comment]
Actually I found no "save" button whatsoever, I had to submit the form through the inspector for it to save the settings. The "generate metadata" does not submit; I added a custom submit to work around this issue in #9

**Comment by trajche** [comment]
Thanks @LizardM4, your pull request has been merged to master.
