### ISSUE TITLE
Wrong $atrb_email value

### ISSUE THREAD

**Issue by larssonper** [trajche/SamlAuth#3]
Hi.

I found an error in SamlAuth.php on line 77. https://github.com/trajche/SamlAuth/blob/master/Auth/SamlAuth.php#L77

`samlauth_name_attribute` should be `samlauth_email_attribute`

Thanks.

Per

**Comment by trajche** [comment]
This is fixed - thanks @larssonper for reporting. Thanks @smacz42 for PR.
