### ISSUE TITLE
Contributing to the package - license questions

### ISSUE THREAD

**Issue by steve-ks** [trajche/SamlAuth#7]
Dear Trajche Kralev,
as I was both forking your project for some modifications as well as using it as a base for creating an InvoicePlane plugin working mostly the same as your package I wanted to ask if it would be fine when I publish my InvoicePlane project under MIT instead of LGPLv3. Though the most important part of the package is the php-saml integration which is also under MIT, I realized that as I used your package as an example it would not be appropriate to just publishing under another license.

The package I am speaking about can be found here:
https://github.com/kingstarter/invoiceplane-saml

Please let me know if this would be fine. I've just published everything and realized afterward that it should have been published under LGPLv3 as I used minimal parts of your code. In case it would not be fine I would either change the license or remove your code parts.

Greetings,
Steve

**Comment by trajche** [comment]
Hi @steve-ks - This is not a problem. Cheers!
