### ISSUE TITLE
Plugin not working with Kanboard 1.1.0

### ISSUE THREAD

**Issue by itsmedani** [trajche/SamlAuth#8]
Hi, 

I unziped the folder in the /plugins directory but when I go to  "Settings → Integrations", I don't have any filed 

![image](https://user-images.githubusercontent.com/26568167/33073806-60eaaf74-cec4-11e7-8fd4-c80e41bc46ca.png)

![image](https://user-images.githubusercontent.com/26568167/33073877-877c8464-cec4-11e7-9ef3-ded67f2caea8.png)

Is the plugin compatible with last vesion of kanboard?

Regards

**Comment by itsmedani** [comment]
Hi, 

i found why. I renamed the folder "SamlAuth-master" to "SamlAuth".

Now I have an error when I try to access to kanboard. HTTP 500.

Do you have any idea why I have this behaviour?

Regards

**Comment by trajche** [comment]
Hi @itsmedani - have you figured this out? I've been inactive but @LizardM4 has submitted a fix for multiple bugs in the plugin - I've just merged it to the master branch. Give it a try.
